import {
  KPI_CARD_DATA,
  RECENT_ACTIVITY_DATA,
  CUSTOMER_DATA,
  PROJECT_DATA,
  TEAM_MEMBER_DATA,
  NOTIFICATION_DATA,
  ANALYTICS_TREND_DATA,
} from './types';

export const ANALYTICS_TRENDS: ANALYTICS_TREND_DATA[] = [
  { name: 'Jan', revenue: 45000, expenses: 22000, profit: 23000, users: 1200, conversion: 2.1, traffic: 18000 },
  { name: 'Feb', revenue: 52000, expenses: 23000, profit: 29000, users: 1450, conversion: 2.3, traffic: 21000 },
  { name: 'Mar', revenue: 61000, expenses: 25000, profit: 36000, users: 1800, conversion: 2.2, traffic: 24700 },
  { name: 'Apr', revenue: 58000, expenses: 27000, profit: 31000, users: 1950, conversion: 2.5, traffic: 23000 },
  { name: 'May', revenue: 73000, expenses: 29000, profit: 44000, users: 2300, conversion: 2.8, traffic: 31200 },
  { name: 'Jun', revenue: 84000, expenses: 31000, profit: 53000, users: 2600, conversion: 2.9, traffic: 36000 },
  { name: 'Jul', revenue: 95000, expenses: 32000, profit: 63000, users: 3100, conversion: 3.1, traffic: 41000 },
  { name: 'Aug', revenue: 91000, expenses: 33000, profit: 58000, users: 3400, conversion: 3.0, traffic: 39500 },
  { name: 'Sep', revenue: 108000, expenses: 35000, profit: 73000, users: 3900, conversion: 3.3, traffic: 48000 },
  { name: 'Oct', revenue: 115000, expenses: 38000, profit: 77000, users: 4400, conversion: 3.4, traffic: 52000 },
  { name: 'Nov', revenue: 132000, expenses: 40000, profit: 92000, users: 5100, conversion: 3.5, traffic: 61000 },
  { name: 'Dec', revenue: 154000, expenses: 42000, profit: 112000, users: 5900, conversion: 3.8, traffic: 72000 },
];

export const GENERAL_KPIS: KPI_CARD_DATA[] = [
  {
    id: 'kpi-mrr',
    title: 'Monthly Recurring Revenue',
    value: '$154,290',
    subtext: 'vs. $132,040 last month',
    change: 16.85,
    changeInterval: 'Month-over-Month',
    sparkline: [110, 115, 112, 120, 125, 128, 134, 132, 142, 145, 148, 154],
    icon: 'DollarSign',
  },
  {
    id: 'kpi-users',
    title: 'Active Accounts',
    value: '5,920',
    subtext: 'vs. 5,110 last month',
    change: 15.85,
    changeInterval: 'Month-over-Month',
    sparkline: [30, 32, 35, 34, 38, 41, 44, 43, 46, 49, 52, 59],
    icon: 'Users',
  },
  {
    id: 'kpi-conversion',
    title: 'Avg. Conversion Rate',
    value: '3.82%',
    subtext: 'vs. 3.54% last month',
    change: 7.9,
    changeInterval: 'Month-over-Month',
    sparkline: [2.1, 2.3, 2.2, 2.5, 2.8, 2.9, 3.1, 3.0, 3.3, 3.4, 3.5, 3.8],
    icon: 'Percent',
  },
  {
    id: 'kpi-churn',
    title: 'Customer Churn Rate',
    value: '1.24%',
    subtext: 'vs. 1.48% last month',
    change: -16.2,
    changeInterval: 'Month-over-Month',
    sparkline: [1.8, 1.7, 1.9, 1.6, 1.5, 1.5, 1.4, 1.6, 1.3, 1.4, 1.4, 1.2],
    icon: 'TrendingDown',
  },
];

export const REGIONAL_ANALYTICS = [
  { countryCode: 'US', countryName: 'United States', users: 2450, percentage: 41, revenue: 63200, coords: [30, 48] },
  { countryCode: 'DE', countryName: 'Germany', users: 890, percentage: 15, revenue: 23100, coords: [49, 39] },
  { countryCode: 'GB', countryName: 'United Kingdom', users: 710, percentage: 12, revenue: 18500, coords: [47, 36] },
  { countryCode: 'CA', countryName: 'Canada', users: 470, percentage: 8, revenue: 12300, coords: [25, 41] },
  { countryCode: 'JP', countryName: 'Japan', users: 410, percentage: 7, revenue: 10800, coords: [77, 49] },
  { countryCode: 'BR', countryName: 'Brazil', users: 350, percentage: 6, revenue: 9200, coords: [38, 68] },
  { countryCode: 'AU', countryName: 'Australia', users: 290, percentage: 5, revenue: 7600, coords: [82, 73] },
  { countryCode: 'SG', countryName: 'Singapore', users: 230, percentage: 4, revenue: 5900, coords: [74, 58] },
  { countryCode: 'ZA', countryName: 'South Africa', users: 120, percentage: 2, revenue: 3100, coords: [52, 70] },
];

export const RECENT_ACTIVITIES: RECENT_ACTIVITY_DATA[] = [
  {
    id: 'act-1',
    user: { name: 'Acme Corp', email: 'billing@acme.com', avatar: '', initials: 'AC', color: 'bg-emerald-500/10 text-emerald-400' },
    action: 'upgraded to',
    target: 'Enterprise Plan',
    time: '2 mins ago',
    amount: '+$4,500/yr',
    status: 'success',
  },
  {
    id: 'act-2',
    user: { name: 'Evelyn Hayes', email: 'evelyn@haze.dev', avatar: '', initials: 'EH', color: 'bg-indigo-500/10 text-indigo-400' },
    action: 'triggered webhook',
    target: 'stripe.payment_intent.succeeded',
    time: '15 mins ago',
    amount: undefined,
    status: 'success',
  },
  {
    id: 'act-3',
    user: { name: 'Vortex Labs', email: 'jake@vortexlabs.io', avatar: '', initials: 'VL', color: 'bg-violet-500/10 text-violet-400' },
    action: 'authorized API key',
    target: 'Live Production Engine',
    time: '42 mins ago',
    amount: undefined,
    status: 'success',
  },
  {
    id: 'act-4',
    user: { name: 'Liam Sterling', email: 'liam@sterling.io', avatar: '', initials: 'LS', color: 'bg-rose-500/10 text-rose-400' },
    action: 'failed login attempt',
    target: 'Admin Console (Vanguard Host)',
    time: '1 hour ago',
    amount: undefined,
    status: 'failed',
  },
  {
    id: 'act-5',
    user: { name: 'Prism Tech', email: 'billing@prism.sh', avatar: '', initials: 'PT', color: 'bg-amber-500/10 text-amber-400' },
    action: 'renewed annual subscription',
    target: 'Team Pro Bundle ($1,200)',
    time: '2 hours ago',
    amount: '+$1,200/yr',
    status: 'success',
  },
  {
    id: 'act-6',
    user: { name: 'Sophia Patel', email: 'sophia@linear.io', avatar: '', initials: 'SP', color: 'bg-cyan-500/10 text-cyan-400' },
    action: 'created pipeline deployment',
    target: 'Production-Mainline-324',
    time: '4 hours ago',
    amount: undefined,
    status: 'success',
  },
  {
    id: 'act-7',
    user: { name: 'Nova Network', email: 'hq@novanet.com', avatar: '', initials: 'NN', color: 'bg-pink-500/10 text-pink-400' },
    action: 'requested API refund',
    target: 'Overage charges on node-124',
    time: '5 hours ago',
    amount: '-$140.00',
    status: 'pending',
  },
];

export const CUSTOMERS_LIST: CUSTOMER_DATA[] = [
  {
    id: 'cust-1',
    name: 'Sarah Connor',
    email: 'sarah.c@cyberdyne.org',
    avatar: '',
    initials: 'SC',
    color: 'bg-blue-500/10 text-blue-400',
    company: 'Skynet Solutions',
    status: 'Active',
    spent: 24890,
    country: 'United States',
    countryCode: 'US',
    dateJoined: '2025-04-12',
  },
  {
    id: 'cust-2',
    name: 'Marcus Aurelius',
    email: 'marcus@stoic.im',
    avatar: '',
    initials: 'MA',
    color: 'bg-amber-500/10 text-amber-400',
    company: 'Roman Empire Inc',
    status: 'Active',
    spent: 18200,
    country: 'Italy',
    countryCode: 'IT',
    dateJoined: '2025-05-01',
  },
  {
    id: 'cust-3',
    name: 'Linus Torvalds',
    email: 'torvalds@kernel.org',
    avatar: '',
    initials: 'LT',
    color: 'bg-emerald-500/10 text-emerald-400',
    company: 'Linux Foundation',
    status: 'Active',
    spent: 45200,
    country: 'Finland',
    countryCode: 'FI',
    dateJoined: '2024-09-18',
  },
  {
    id: 'cust-4',
    name: 'Ada Lovelace',
    email: 'ada@bernoulli.calc',
    avatar: '',
    initials: 'AL',
    color: 'bg-indigo-500/10 text-indigo-400',
    company: 'Analytical Engines Ltd',
    status: 'Active',
    spent: 29400,
    country: 'United Kingdom',
    countryCode: 'GB',
    dateJoined: '2024-11-23',
  },
  {
    id: 'cust-5',
    name: 'Hideo Kojima',
    email: 'kojima@kojipro.co.jp',
    avatar: '',
    initials: 'HK',
    color: 'bg-rose-500/10 text-rose-400',
    company: 'Kojima Productions',
    status: 'Active',
    spent: 14500,
    country: 'Japan',
    countryCode: 'JP',
    dateJoined: '2025-01-30',
  },
  {
    id: 'cust-6',
    name: 'Richard Feynman',
    email: 'rpf@caltech.edu',
    avatar: '',
    initials: 'RF',
    color: 'bg-violet-500/10 text-violet-400',
    company: 'Quantum Dynamics',
    status: 'Inactive',
    spent: 8900,
    country: 'United States',
    countryCode: 'US',
    dateJoined: '2024-06-15',
  },
  {
    id: 'cust-7',
    name: 'Nikola Tesla',
    email: 'nikola@alternating.co',
    avatar: '',
    initials: 'NT',
    color: 'bg-cyan-500/10 text-cyan-400',
    company: 'Wardenclyffe Lab',
    status: 'Pending',
    spent: 3100,
    country: 'Croatia',
    countryCode: 'HR',
    dateJoined: '2026-05-18',
  },
  {
    id: 'cust-8',
    name: 'Marie Curie',
    email: 'marie@radium.univ-paris.fr',
    avatar: '',
    initials: 'MC',
    color: 'bg-pink-500/10 text-pink-400',
    company: 'Paris Research Inst.',
    status: 'Active',
    spent: 19800,
    country: 'France',
    countryCode: 'FR',
    dateJoined: '2025-03-04',
  },
];

export const PROJECTS_LIST: PROJECT_DATA[] = [
  {
    id: 'proj-1',
    name: 'Stripe Gateway Upgrade',
    description: 'Upgrading the core billing framework to support Stripe v3 webhooks, SCA regulations, and multi-currency billing.',
    status: 'In Progress',
    progress: 74,
    budget: 45000,
    spent: 38200,
    dueDate: '2026-06-30',
    owner: { name: 'Elisha Vance', avatar: '', initials: 'EV', color: 'bg-orange-500/10 text-orange-400' },
    team: ['Linus Torvalds', 'Ada Lovelace'],
  },
  {
    id: 'proj-2',
    name: 'Data Pipeline Optimization',
    description: 'Refactoring the ClickHouse ingestion worker to reduce pipeline latency below 50ms for live telemetry data.',
    status: 'Completed',
    progress: 100,
    budget: 24000,
    spent: 23150,
    dueDate: '2026-05-15',
    owner: { name: 'Jenny Watson', avatar: '', initials: 'JW', color: 'bg-purple-500/10 text-purple-400' },
    team: ['Sarah Connor', 'Nikola Tesla'],
  },
  {
    id: 'proj-3',
    name: 'Global UI Design Refresh',
    description: 'Applying a high-fidelity dark glassmorphic design language across analytical panels, maps, and reporting pipelines.',
    status: 'In Review',
    progress: 95,
    budget: 18000,
    spent: 17500,
    dueDate: '2026-06-12',
    owner: { name: 'Leslie Alexander', avatar: '', initials: 'LA', color: 'bg-pink-500/10 text-pink-400' },
    team: ['Marie Curie', 'Ada Lovelace', 'Hideo Kojima'],
  },
  {
    id: 'proj-4',
    name: 'Enterprise Multi-Tenant Auth',
    description: 'Developing custom SAML, OIDC, and SCIM directory syncing integration mechanisms for Global 2000 clients.',
    status: 'Planning',
    progress: 12,
    budget: 95000,
    spent: 8400,
    dueDate: '2026-09-01',
    owner: { name: 'Evelyn Hayes', avatar: '', initials: 'EH', color: 'bg-indigo-500/10 text-indigo-400' },
    team: ['Marcus Aurelius', 'Linus Torvalds'],
  },
  {
    id: 'proj-5',
    name: 'AI Smart Forecasting Module',
    description: 'Prototyping linear and deep predictive forecasting algorithms on SaaS churn metrics using Google Gemini models.',
    status: 'On Hold',
    progress: 45,
    budget: 62000,
    spent: 41200,
    dueDate: '2026-10-15',
    owner: { name: 'Richard Feynman', avatar: '', initials: 'RF', color: 'bg-indigo-500/10 text-indigo-400' },
    team: ['Marie Curie', 'Richard Feynman'],
  },
];

export const TEAM_MEMBERS: TEAM_MEMBER_DATA[] = [
  {
    id: 'team-1',
    name: 'Elisha Vance',
    email: 'elisha@ideaflow.io',
    avatar: '',
    initials: 'EV',
    color: 'bg-orange-500/10 text-orange-400',
    role: 'Owner',
    status: 'Active',
    lastActive: 'Just now',
  },
  {
    id: 'team-2',
    name: 'Jenny Watson',
    email: 'jenny.w@ideaflow.io',
    avatar: '',
    initials: 'JW',
    color: 'bg-purple-500/10 text-purple-400',
    role: 'Admin',
    status: 'Active',
    lastActive: '5m ago',
  },
  {
    id: 'team-3',
    name: 'Leslie Alexander',
    email: 'leslie.a@ideaflow.io',
    avatar: '',
    initials: 'LA',
    color: 'bg-pink-500/10 text-pink-400',
    role: 'Developer',
    status: 'Active',
    lastActive: '12m ago',
  },
  {
    id: 'team-4',
    name: 'Evelyn Hayes',
    email: 'evelyn.h@ideaflow.io',
    avatar: '',
    initials: 'EH',
    color: 'bg-indigo-500/10 text-indigo-400',
    role: 'Developer',
    status: 'Offline',
    lastActive: '3h ago',
  },
  {
    id: 'team-5',
    name: 'Kristin Wood',
    email: 'kristin.w@ideaflow.io',
    avatar: '',
    initials: 'KW',
    color: 'bg-emerald-500/10 text-emerald-400',
    role: 'Billing Manager',
    status: 'Active',
    lastActive: '1h ago',
  },
  {
    id: 'team-6',
    name: 'David Lightman',
    email: 'david@wargames.io',
    avatar: '',
    initials: 'DL',
    color: 'bg-rose-500/10 text-rose-400',
    role: 'Viewer',
    status: 'Invited',
    lastActive: 'Never',
  },
];

export const NOTIFICATIONS_LIST: NOTIFICATION_DATA[] = [
  {
    id: 'not-1',
    title: 'New Enterprise Lead',
    description: 'Cyberdyne Systems requested custom pricing for 5,000 corporate seats.',
    time: '2 mins ago',
    type: 'success',
    read: false,
    category: 'activity',
  },
  {
    id: 'not-2',
    title: 'API Rate Limit Warning',
    description: 'Workspace "Vanguard Hub" reached 92% of their hourly API route allowance.',
    time: '15 mins ago',
    type: 'warning',
    read: false,
    category: 'system',
  },
  {
    id: 'not-3',
    title: 'SAML SSO Certification Updated',
    description: 'Microsoft Entra ID certificate successfully re-issued and verified by sysadmin.',
    time: '1 hour ago',
    type: 'info',
    read: true,
    category: 'security',
  },
  {
    id: 'not-4',
    title: 'Failed Subscription Bill',
    description: 'Recurring transaction for client "Richard Feynman" failed (error code CardExpired).',
    time: '5 hours ago',
    type: 'error',
    read: false,
    category: 'billing',
  },
  {
    id: 'not-5',
    title: 'Database Compression Succeeded',
    description: 'Index structures defragmented. Restores 45.2 GB of solid state drive allocation.',
    time: '1 day ago',
    type: 'success',
    read: true,
    category: 'system',
  },
  {
    id: 'not-6',
    title: 'New API Key Provisioned',
    description: 'Developer Leslie Alexander created high-clearance production key "deploy-tunnels-4".',
    time: '2 days ago',
    type: 'info',
    read: true,
    category: 'security',
  },
];

export const SAAS_PLANS = [
  {
    name: 'Starter',
    price: '$49',
    interval: 'mo',
    description: 'Ideal for early stage startups proving market fit.',
    features: [
      'Up to 1,000 monthly active users',
      'Real-time core KPI analytics dashboard',
      '14-day history storage duration',
      'Email support channel (24h response SLA)',
      '1 Webhook webhook dispatch connector',
    ],
    badge: 'Popular for Bootstrappers',
    current: false,
  },
  {
    name: 'Growth Pro',
    price: '$129',
    interval: 'mo',
    description: 'Perfect for rapidly scaling SaaS platforms looking for deeper metrics.',
    features: [
      'Up to 10,000 monthly active users',
      'Advanced cohort, churn, & funnels tracking',
      'Unlimited history retention storage duration',
      'Priority live database connections & support (4h SLA)',
      '15 concurrent Webhook pipeline connectors',
      'Granular team permission levels & scopes',
      'Automated PDF reporting scheduler engine',
    ],
    badge: 'Most Popular Choice',
    current: true,
  },
  {
    name: 'Enterprise Apex',
    price: '$499',
    interval: 'mo',
    description: 'Custom build for corporate organizations needing high capacity and custom SLAs.',
    features: [
      'Unlimited monthly active users quota',
      'Full custom SAML / OIDC Single Sign On options',
      '99.99% operational uptimes SLA agreement',
      'Dedicated Customer Success specialist',
      'Direct custom ClickHouse read-replica querying',
      'Custom predictive Gemini forecasting algorithms',
      'Audit log log trails auditing',
    ],
    badge: 'Enterprise Performance',
    current: false,
  },
];
